name: Deploy to GitHub Pages

on:
  # 推送到main分支时触发
  push:
    branches:
      - main

  # 允许手动触发
  workflow_dispatch:

# 设置GITHUB_TOKEN权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置Pages
        uses: actions/configure-pages@v4

      - name: 上传Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
